# Generated by Django 5.2.1 on 2025-08-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_replaycomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplayComment',
        ),
    ]
